# netlify.toml
[build]
  publish = "." # This means Netlify will serve files directly from the root of your repo

[functions]
  directory = "netlify/functions" # This is the folder where Netlify will find your functions
  node_bundler = "esbuild" # Recommended for faster Python function builds
  # Removed: python_version = "3.9" from here
