[build]
  publish = "." # Your HTML files are in the root

[functions]
  directory = "functions/" # Your functions are nested inside 'netlify' folder
  node_bundler = "esbuild" # Optional but recommended
