# netlify.toml
[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# This plugin automatically installs Node.js dependencies
# within your Netlify Functions directory (netlify/functions/package.json)
[[plugins]]
package = "@netlify/plugin-functions-install-core"
